
GET http://localhost:3000/api/v2/analytics?fromdate=2008-05-12
API_KEY: a1b2c3d4e5
###

POST http://localhost:3000/api/v2/warehouses
API_KEY: j6k7l8m9n0
Content-Type: application/json

{
    "code": "YQZZNL56",
    "name": "Heemskerk cargo hub",
    "address": "Karlijndreef 281",
    "zip": "4002 AS",
    "city": "Heemskerk",
    "province": "Friesland",
    "country": "NL",
    "contact": {
      "name": "Fem Keijzer",
      "phone": "(078) 0013363",
      "email": "blamore@example.net"
    }
  }
###

GET  http://localhost:3000/api/v2/warehouses/59
API_KEY: j6k7l8m9n0

###

POST http://localhost:3000/api/v2/locations
API_KEY: j6k7l8m9n0
Content-Type: application/json

{
  "WarehouseId": 59,
  "Code": "A.1.0",
  "Name": "Row: A, Rack: 1, Shelf: 0"
}
###

POST http://localhost:3000/api/v2/locations
API_KEY: j6k7l8m9n0
Content-Type: application/json

{
  "WarehouseId": 59,
  "Code": "A.2.0",
  "Name": "Row: A, Rack: 2, Shelf: 0"
}
###
POST http://localhost:3000/api/v2/locations
API_KEY: j6k7l8m9n0
Content-Type: application/json

{
  "WarehouseId": 59,
  "Code": "A.3.0",
  "Name": "Row: A, Rack: 3, Shelf: 0"
}
###
POST http://localhost:3000/api/v2/locations
API_KEY: j6k7l8m9n0
Content-Type: application/json

{
  "WarehouseId": 59,
  "Code": "A.4.0",
  "Name": "Row: A, Rack: 4, Shelf: 0"
}
###
POST http://localhost:3000/api/v2/locations
API_KEY: j6k7l8m9n0
Content-Type: application/json

{
  "WarehouseId": 59,
  "Code": "A.5.0",
  "Name": "Row: A, Rack: 5, Shelf: 0"
}
###

GET  http://localhost:3000/api/v2/warehouses/59/locations
API_KEY: j6k7l8m9n0

###

PUT http://localhost:3000/api/v2/warehouses/59
API_KEY: j6k7l8m9n0
Content-Type: application/json

{
    "code": "YQZZNL56",
    "name": "Heemskerk cargo hub",
    "address": "Karlijndreef 281",
    "zip": "4002 AS",
    "city": "Heemskerk",
    "province": "Friesland",
    "country": "NL",
    "contact": {
      "name": "veranderd naam",
      "phone": "(078) 412345",
      "email": "blamore@example.net"
    }
}
###

PUT  http://localhost:3000/api/v2/warehouses/59
API_KEY: a1b2c3d4e5
Content-Type: application/json

{
    "code": "YQZZNL56",
    "name": "Heemskerk cargo hub",
    "address": "Karlijndreef 281",
    "zip": "4002 AS",
    "city": "Heemskerk",
    "province": "Friesland",
    "country": "NL",
    "contact": {
      "name": "veranderd naam",
      "phone": "(078) 0013363",
      "email": "blamore@example.net"
    }
  }
###



DELETE  http://localhost:3000/api/v2/warehouses/59
API_KEY: a1b2c3d4e5

###

GET  http://localhost:3000/api/v2/warehouses/59
API_KEY: a1b2c3d4e5

###



GET  http://localhost:3000/api/v2/warehouses/59/locations
API_KEY: j6k7l8m9n0

###

GET  http://localhost:3000/api/v2/warehouses/1/locations
API_KEY: j6k7l8m9n0

###

