GET http://localhost:3000/api/v2/inventories
API_KEY: a1b2c3d4e5
###


GET http://localhost:3000/api/v2/inventories/1
API_KEY: a1b2c3d4e5
###

POST  http://localhost:3000/api/v2/inventories
API_KEY: a1b2c3d4e5
Content-Type: application/json

{"id": 100000, "itemId": "P000001", "description": "Face-to-face clear-thinking complexity", "itemReference": "sjQ23408K", "locations": [3211, 24700, 14123, 19538, 31071, 24701, 11606, 11817], "totalOnHand": 262, "totalExpected": 0, "totalOrdered": 80, "totalAllocated": 41, "totalAvailable": 141, "lowStockThreshold": 10, "isLowStock": false}
###
POST  http://localhost:3000/api/v2/inventories/load/inventories.json
###

PUT   http://localhost:3000/api/v2/inventories/1
API_KEY: a1b2c3d4e5
Content-Type: application/json

{"id": 1, "itemId": "P000001", "description": "quack", "itemReference": "sjQ23408K", "locations": [3211, 24700, 14123, 19538, 31071, 24701, 11606, 11817], "totalOnHand": 5, "totalExpected": 0, "totalOrdered": 80, "totalAllocated": 41, "totalAvailable": 141, "lowStockThreshold": 10, "isLowStock": true}
###

PUT   http://localhost:3000/api/v2/inventories/1
API_KEY: a1b2c3d4e5
Content-Type: application/json

{"id": 1, "item_id": "P000001", "description": "quack", "item_reference": "sjQ23408K", "locations": [3211, 24700, 14123, 19538, 31071, 24701, 11606, 11817], "total_on_hand": 262, "total_expected": 0, "total_ordered": 80, "total_allocated": 41, "total_available": 141}
###

GET http://localhost:3000/api/v2/inventories/lowstock?threshold=2
API_KEY: a1b2c3d4e5
###

GET http://localhost:3000/api/v2/inventories/lowstock
API_KEY: a1b2c3d4e5
###

DELETE  http://localhost:3000/api/v2/inventories/1
API_KEY: a1b2c3d4e5
###
