name: Release Drafter

on:
  push:
    branches:
      - main

jobs:
  update-release-draft:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Run Release Drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
