name: Release Drafter

on:
  push:
    branches:
      - main
      - release-test

permissions:
  contents: read

jobs:
  update-release-draft:
    name: Update Release Draft
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Release Drafter
        uses: release-drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
