name: Release Drafter

on:
  push:
    branches:
      - main
      - release-test

permissions:
  contents: read

jobs:
  update-release-draft:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - name: Release Drafter
        uses: release-drafter/release-drafter@v6
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
