# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: "💥 Breaking Changes"
      labels:
        - breaking-change
    - title: "🚀 New Features"
      labels:
        - enhancement
    - title: "🚧 Testing"
      labels:
        - tests
    - title: "🐛 Bug Fixes"
      labels:
        - bug
    - title: "✅ Other Changes"
      labels:
        - "*"
